name = "inclusivai-api"
main = "src/index.ts"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[kv_namespaces]]
binding = "INCLUSIVAI_CACHE"
id = "130b0bfc04e74f5293abc632fbb84b33"
